# Generated by Django 4.0 on 2022-01-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='user',
            new_name='tag',
        ),
    ]
